font=jetbrainsmono nerd font:size=14
pad=4x4 

[colors-dark]
foreground=dddddd  # gray9
background=101010  # main_background

## Normal/regular colors (color palette 0-7)
regular0=080808  # gray1 (black)
regular1=d70000  # red
regular2=789978  # green
regular3=abab77  # yellow
regular4=7788aa  # blue
regular5=708090  # lack (used for magenta to keep it muted)
regular6=7a7a7a  # gray6 (used for cyan to keep it muted)
regular7=aaaaaa  # gray7 (white)

## Bright colors (color palette 8-15)
bright0=444444   # gray4 (bright black)
bright1=ffaa88   # orange (acting as bright red)
bright2=789978   # green (bright green)
bright3=abab77   # yellow (bright yellow)
bright4=7788aa   # blue (bright blue)
bright5=708090   # lack (bright magenta)
bright6=deeeed   # luster (bright cyan)
bright7=dddddd   # gray9 (bright white)

## dimmed colors (see foot.ini(5) man page)
dim0=ffaa88      # orange
dim1=d70000      # red

alpha=1
